name: module3_task5
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build-artifact:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cd module3_task5 && ./setup.sh
      - run: cd module3_task5 && make build
      - run: cd module3_task5 && make unit-tests
      - run: cd module3_task5 && make integration-tests
      - run: cd module3_task5 && make validate
      - run: cd module3_task5 && make help
      - run: cd module3_task5 && make lint
      - run: cd module3_task5 && make package
      - uses: actions/upload-artifact@v3
        with:
          name: awesome-website
          path: ./module3_task5/awesome-website.zip
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './module3_task5/dist'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "ðŸš€ Deployed on"
          publish-message: "ðŸŽ‰ Published on"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
  build-release:
    permissions:
      contents: write
    needs: build-artifact
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Download awesome-website zip file
        uses: actions/download-artifact@v3
        with:
          name: awesome-website
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: awesome-website.zip
          body_path: ./module3_task5/DEPLOY.md
