name: module3_task4
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build-artifact:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cd module3_task4 && ./setup.sh
      - run: cd module3_task4 && make build
      - run: cd module3_task4 && make unit-tests
      - run: cd module3_task4 && make integration-tests
      - run: cd module3_task4 && make validate
      - run: cd module3_task4 && make help
      - run: cd module3_task4 && make lint
      - run: cd module3_task4 && make package
      - uses: actions/upload-artifact@v3
        with:
          name: awesome-website
          path: ./module3_task4/awesome-website.zip
  build-release:
    permissions:
      contents: write
    needs: build-artifact
    if: startsWith(github.ref, 'refs/tags/1.0.0')
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Download awesome-website.zip file
        uses: actions/download-artifact@v3
        with:
          name: awesome-website
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: awesome-website.zip
          body_path: ./module3_task4/DEPLOY.md
